name: Main Workflow
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: ./actions/build
    - name: Unit Tests
      uses: ./actions/test
    - name: Code Style Analysis
      uses: ./actions/phpcs

